name: "Andrew John Hill"
description: "Professional website of Andrew John Hill"

exclude: ["social icons (unused)"]

url: "http://www.andrewjohnhill.com"

paginate: 5
paginate_path: blog/page:num

plugins: [jekyll-paginate]

markdown: kramdown
permalink: pretty
highlighter: rouge
